import type { TaskRow } from '../../components/task-list/task-row';

/** 初回 Firestore 投入用デモデータ（開発ビルド・コレクション空のときのみ） */
export const TASK_SEED_ROWS_RAW: TaskRow[] = [
    {
      managementNumber: 'PRJ-2026-001',
      name: '顧客ポータル刷新',
      type: '課題',
      managementNo: 'TK-2026-001',
      taskname: '新規顧客向け提案資料のレビュー',
      taskContent: '価格表・納期案の最終確認。上長承認後に顧客送付。',
      creator: '山田太郎',
      departments: ['マーケティング部'],
      members: '橋本拓海',
      endDate: '2026-06-08',
      priority: '高',
      status: '着手中',
      registeredOn: '2026-04-10',
      startedOn: '2026-04-12',
      completedOn: '',
      approver: '',
      progressPercent: 60,
      lastUpdatedAt: '2026-05-08',
      lastUpdatedBy: '橋本拓海',
      participants: [{ department: 'マーケティング部', name: '橋本拓海' }],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-04-10', by: '山田太郎', summary: '課題を新規登録' },
        { at: '2026-05-08', by: '橋本拓海', summary: '進捗を更新' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-001',
      name: '顧客ポータル刷新',
      type: 'バグ',
      managementNo: 'TK-2026-002',
      taskname: 'ログイン画面の表示崩れ調査',
      taskContent: 'Safari 最新版のみ再現。再現手順をチケットに記載済み。',
      creator: '高橋健',
      departments: ['開発部'],
      members: '高橋健、鈴木一郎',
      endDate: '2026-06-12',
      priority: '中',
      status: '確認待ち',
      registeredOn: '2026-04-18',
      startedOn: '2026-04-20',
      completedOn: '',
      approver: '鈴木一郎',
      progressPercent: 90,
      lastUpdatedAt: '2026-05-07',
      lastUpdatedBy: '高橋健',
      participants: [
        { department: '開発部', name: '高橋健' },
        { department: '開発部', name: '鈴木一郎' },
      ],
      resourceFolders: [],
      updateHistory: [{ at: '2026-04-18', by: '高橋健', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-002',
      name: '営業支援ダッシュボード',
      type: '課題',
      managementNo: 'TK-2026-003',
      taskname: 'オフィス備品の発注',
      taskContent: 'A4 用紙 10 箱、トナー交換用カートリッジ。',
      creator: '伊藤誠',
      departments: ['総務'],
      members: '伊藤誠、渡辺千夏',
      endDate: '2026-06-20',
      priority: '低',
      status: '未着手',
      registeredOn: '2026-04-25',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-04-25',
      lastUpdatedBy: '渡辺千夏',
      participants: [
        { department: '総務', name: '伊藤誠' },
        { department: '総務', name: '渡辺千夏' },
      ],
      resourceFolders: [],
      updateHistory: [{ at: '2026-04-25', by: '伊藤誠', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-016',
      name: '社内 FAQ ポータル',
      type: '課題',
      managementNo: 'TK-2026-004',
      taskname: 'KPI 定義ワークショップ準備',
      taskContent: '各部門からヒアリング項目を回収し、アジェンダ案を作成する。',
      creator: '佐藤花子',
      departments: ['営業第一部'],
      members: '山田太郎',
      endDate: '2026-06-25',
      priority: '中',
      status: '未着手',
      registeredOn: '2026-05-02',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-02',
      lastUpdatedBy: '佐藤花子',
      participants: [{ department: '営業第一部', name: '山田太郎' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-02', by: '佐藤花子', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-017',
      name: 'モバイル印刷連携',
      type: '改善',
      managementNo: 'TK-2026-005',
      taskname: 'iOS での印刷プレビュー検証',
      taskContent: 'AirPrint 経由とアプリ内プレビューの差分をドキュメント化。',
      creator: '高橋健',
      departments: ['開発部'],
      members: '高橋健、鈴木一郎',
      endDate: '2026-07-03',
      priority: '高',
      status: '着手中',
      registeredOn: '2026-04-25',
      startedOn: '2026-05-06',
      completedOn: '',
      approver: '',
      progressPercent: 40,
      lastUpdatedAt: '2026-05-12',
      lastUpdatedBy: '鈴木一郎',
      participants: [
        { department: '開発部', name: '高橋健' },
        { department: '開発部', name: '鈴木一郎' },
      ],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-04-25', by: '高橋健', summary: '課題を新規登録' },
        { at: '2026-05-12', by: '鈴木一郎', summary: '検証結果を追記' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-018',
      name: 'アクセス権レビュー（年度版）',
      type: '課題',
      managementNo: 'TK-2026-006',
      taskname: '権限マトリクスドラフト作成',
      taskContent: '基幹 12 システム分のロール一覧をスプレッドシートに集約。',
      creator: '鈴木一郎',
      departments: ['開発部'],
      members: '鈴木一郎',
      endDate: '2026-06-30',
      priority: '急',
      status: '確認待ち',
      registeredOn: '2026-04-12',
      startedOn: '2026-04-16',
      completedOn: '',
      approver: '山田太郎',
      progressPercent: 95,
      lastUpdatedAt: '2026-05-09',
      lastUpdatedBy: '鈴木一郎',
      participants: [{ department: '開発部', name: '鈴木一郎' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-04-12', by: '鈴木一郎', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-019',
      name: 'VPN クライアント更新',
      type: 'バグ',
      managementNo: 'TK-2026-007',
      taskname: '旧クライアントの切断エラー調査',
      taskContent: 'ログ採取済み。ベンダー回答待ちのためクローズ。',
      creator: '高橋健',
      departments: ['開発部'],
      members: '高橋健',
      endDate: '2026-07-10',
      priority: '高',
      status: '完了',
      registeredOn: '2026-03-12',
      startedOn: '2026-03-18',
      completedOn: '2026-07-10',
      approver: '',
      progressPercent: 100,
      lastUpdatedAt: '2026-07-10',
      lastUpdatedBy: '高橋健',
      participants: [{ department: '開発部', name: '高橋健' }],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-07-10', by: '高橋健', summary: '課題を完了' },
        { at: '2026-03-12', by: '高橋健', summary: '課題を新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-020',
      name: 'メール署名統一ツール',
      type: '課題',
      managementNo: 'TK-2026-008',
      taskname: 'メールテンプレ差分一覧',
      taskContent: '営業第一部・第二部の現行 HTML 署名を比較し差分タグを洗い出す。',
      creator: '山田太郎',
      departments: ['営業第一部'],
      members: '山田太郎',
      endDate: '2026-07-22',
      priority: '低',
      status: '保留',
      registeredOn: '2026-04-29',
      startedOn: '2026-05-01',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-06',
      lastUpdatedBy: '山田太郎',
      participants: [{ department: '営業第一部', name: '山田太郎' }],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-05-06', by: '坂本悠真', summary: '優先度変更のため保留' },
        { at: '2026-04-29', by: '山田太郎', summary: '課題を新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-001',
      name: '顧客ポータル刷新',
      type: '改善',
      managementNo: 'TK-2026-009',
      taskname: 'API 認証フロー統合テスト',
      taskContent: 'OIDC 連携の E2E シナリオをステージングで実施し結果を記録する。',
      creator: '鈴木一郎',
      departments: ['開発部'],
      members: '鈴木一郎、高橋健',
      endDate: '2026-06-18',
      priority: '高',
      status: '着手中',
      registeredOn: '2026-05-20',
      startedOn: '2026-05-22',
      completedOn: '',
      approver: '',
      progressPercent: 35,
      lastUpdatedAt: '2026-06-01',
      lastUpdatedBy: '高橋健',
      participants: [
        { department: '開発部', name: '鈴木一郎' },
        { department: '開発部', name: '高橋健' },
      ],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-20', by: '鈴木一郎', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-002',
      name: '営業支援ダッシュボード',
      type: '課題',
      managementNo: 'TK-2026-010',
      taskname: 'ダッシュボード KPI 定義',
      taskContent: 'パイプライン転換率と活動量の指標案を営業部門で合意する。',
      creator: '山田太郎',
      departments: ['営業第一部'],
      members: '山田太郎',
      endDate: '2026-06-28',
      priority: '中',
      status: '着手中',
      registeredOn: '2026-05-15',
      startedOn: '2026-05-18',
      completedOn: '',
      approver: '',
      progressPercent: 50,
      lastUpdatedAt: '2026-05-28',
      lastUpdatedBy: '山田太郎',
      participants: [{ department: '営業第一部', name: '山田太郎' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-15', by: '山田太郎', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2025-088',
      name: '社内文書テンプレート整備',
      type: '課題',
      managementNo: 'TK-2026-011',
      taskname: 'テンプレ改訂履歴の整理',
      taskContent: '契約書・稟議テンプレの版管理ルールをドキュメント化し共有する。',
      creator: '佐藤花子',
      departments: ['営業第二部'],
      members: '佐藤花子',
      endDate: '2026-06-25',
      priority: '低',
      status: '完了',
      registeredOn: '2026-05-01',
      startedOn: '2026-05-05',
      completedOn: '2026-06-25',
      approver: '',
      progressPercent: 100,
      lastUpdatedAt: '2026-06-25',
      lastUpdatedBy: '佐藤花子',
      participants: [{ department: '営業第二部', name: '佐藤花子' }],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-06-25', by: '佐藤花子', summary: '課題を完了' },
        { at: '2026-05-01', by: '佐藤花子', summary: '課題を新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-010',
      name: 'インフラ監視強化',
      type: '課題',
      managementNo: 'TK-2026-012',
      taskname: 'アラート閾値ドラフト見直し',
      taskContent: 'CPU・メモリ・ディスクの閾値案を監視チームとレビューする。',
      creator: '鈴木一郎',
      departments: ['開発部'],
      members: '鈴木一郎',
      endDate: '2026-07-01',
      priority: '急',
      status: '保留',
      registeredOn: '2026-04-20',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-01',
      lastUpdatedBy: '鈴木一郎',
      participants: [{ department: '開発部', name: '鈴木一郎' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-04-20', by: '鈴木一郎', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-015',
      name: '新規顧客オンボーディング',
      type: '改善',
      managementNo: 'TK-2026-013',
      taskname: 'オンボーディングチェックリスト作成',
      taskContent: '契約後 30 日以内の標準タスク一覧をたたき台として作成する。',
      creator: '山田太郎',
      departments: ['営業第一部'],
      members: '山田太郎',
      endDate: '2026-06-22',
      priority: '高',
      status: '未着手',
      registeredOn: '2026-05-12',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-12',
      lastUpdatedBy: '山田太郎',
      participants: [{ department: '営業第一部', name: '山田太郎' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-12', by: '山田太郎', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-016',
      name: '社内 FAQ ポータル',
      type: '課題',
      managementNo: 'TK-2026-014',
      taskname: 'FAQ カテゴリ設計',
      taskContent: '部門横断で検索しやすいカテゴリツリー案を作成する。',
      creator: '佐藤花子',
      departments: ['営業第二部'],
      members: '佐藤花子',
      endDate: '2026-07-08',
      priority: '中',
      status: '未着手',
      registeredOn: '2026-05-18',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-18',
      lastUpdatedBy: '佐藤花子',
      participants: [{ department: '営業第二部', name: '佐藤花子' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-18', by: '佐藤花子', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-017',
      name: 'モバイル印刷連携',
      type: '課題',
      managementNo: 'TK-2026-015',
      taskname: '利用ガイド文面作成',
      taskContent: 'スマホからの印刷手順を部門向けヘルプページ用に整える。',
      creator: '石川奈々',
      departments: ['マーケティング部'],
      members: '石川奈々',
      endDate: '2026-07-14',
      priority: '中',
      status: '着手中',
      registeredOn: '2026-05-25',
      startedOn: '2026-05-28',
      completedOn: '',
      approver: '',
      progressPercent: 20,
      lastUpdatedAt: '2026-06-05',
      lastUpdatedBy: '石川奈々',
      participants: [{ department: 'マーケティング部', name: '石川奈々' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-25', by: '石川奈々', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-018',
      name: 'アクセス権レビュー（年度版）',
      type: '課題',
      managementNo: 'TK-2026-016',
      taskname: '棚卸結果サマリ作成',
      taskContent: '経理向けに不要アカウント一覧と対応方針を 1 枚にまとめる。',
      creator: '井上剛',
      departments: ['経理部'],
      members: '井上剛',
      endDate: '2026-07-06',
      priority: '急',
      status: '着手中',
      registeredOn: '2026-05-10',
      startedOn: '2026-05-12',
      completedOn: '',
      approver: '',
      progressPercent: 45,
      lastUpdatedAt: '2026-05-30',
      lastUpdatedBy: '井上剛',
      participants: [{ department: '経理部', name: '井上剛' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-10', by: '井上剛', summary: '課題を新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-019',
      name: 'VPN クライアント更新',
      type: '課題',
      managementNo: 'TK-2026-017',
      taskname: '展開レポート最終確認',
      taskContent: '全社展開の完了率と未更新端末リストを最終版として確定する。',
      creator: '高橋健',
      departments: ['開発部'],
      members: '高橋健',
      endDate: '2026-07-08',
      priority: '高',
      status: '完了',
      registeredOn: '2026-06-20',
      startedOn: '2026-06-22',
      completedOn: '2026-07-08',
      approver: '',
      progressPercent: 100,
      lastUpdatedAt: '2026-07-08',
      lastUpdatedBy: '高橋健',
      participants: [{ department: '開発部', name: '高橋健' }],
      resourceFolders: [],
      updateHistory: [
        { at: '2026-07-08', by: '高橋健', summary: '課題を完了' },
        { at: '2026-06-20', by: '高橋健', summary: '課題を新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-020',
      name: 'メール署名統一ツール',
      type: '改善',
      managementNo: 'TK-2026-018',
      taskname: 'テンプレ配布手順書作成',
      taskContent: '部署別テンプレの配布・差し替え手順を Wiki 形式で整備する。',
      creator: '佐藤花子',
      departments: ['営業第二部'],
      members: '佐藤花子',
      endDate: '2026-07-20',
      priority: '低',
      status: '未着手',
      registeredOn: '2026-05-08',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-08',
      lastUpdatedBy: '佐藤花子',
      participants: [{ department: '営業第二部', name: '佐藤花子' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-08', by: '佐藤花子', summary: '課題を新規登録' }],
    },
    {
      managementNumber: '',
      name: '',
      parentTaskManagementNo: 'TK-2026-001',
      type: '課題',
      managementNo: 'TK-2026-001-S1',
      taskname: '価格表ドラフト確認',
      taskContent: '営業部門向け価格表の数値チェック。',
      creator: '山田太郎',
      departments: ['マーケティング部'],
      members: '伊藤誠',
      endDate: '2026-06-05',
      priority: '中',
      status: '着手中',
      registeredOn: '2026-05-10',
      startedOn: '2026-05-11',
      completedOn: '',
      approver: '',
      progressPercent: 40,
      lastUpdatedAt: '2026-05-12',
      lastUpdatedBy: '伊藤誠',
      participants: [{ department: 'マーケティング部', name: '伊藤誠' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-10', by: '山田太郎', summary: '子課題を新規登録' }],
    },
    {
      managementNumber: '',
      name: '',
      parentTaskManagementNo: 'TK-2026-001',
      type: '課題',
      managementNo: 'TK-2026-001-S2',
      taskname: '納期案の法務確認',
      taskContent: '契約条項と納期スケジュールの整合。',
      creator: '山田太郎',
      departments: ['マーケティング部'],
      members: '渡辺千夏',
      endDate: '2026-06-08',
      priority: '高',
      status: '未着手',
      registeredOn: '2026-05-10',
      startedOn: '',
      completedOn: '',
      approver: '',
      progressPercent: 0,
      lastUpdatedAt: '2026-05-10',
      lastUpdatedBy: '山田太郎',
      participants: [{ department: 'マーケティング部', name: '渡辺千夏' }],
      resourceFolders: [],
      updateHistory: [{ at: '2026-05-10', by: '山田太郎', summary: '子課題を新規登録' }],
    },
];
