import type { ProjectRow } from '../../components/project-list/project-row';

/** 初回 Firestore 投入用デモデータ（コレクションが空のときのみ） */
export const PROJECT_SEED_ROWS: ProjectRow[] = [
  {
      managementNumber: 'PRJ-2026-001',
      name: '顧客ポータル刷新',
      description: '既存顧客向けポータルの UI 刷新と認証基盤の統合を行う。',
      departments: ['開発部', 'マーケティング部'],
      endDate: '2026-07-15',
      priority: '高',
      registeredAt: '2026-03-01',
      workStartDate: '2026-04-01',
      completedAt: '',
      status: '着手中',
      participants: [
        { department: '開発部', name: '鈴木一郎', role: '責任者' },
        { department: '開発部', name: '高橋健', role: 'メンバー' },
        { department: 'マーケティング部', name: '橋本拓海', role: 'メンバー' },
      ],
      members: ['鈴木一郎', '高橋健', '橋本拓海'],
      progressPercent: 42,
      approver: '佐藤花子',
      milestones: [
        { title: '要件定義', targetDate: '2026-06-10' },
        { title: 'β版公開', targetDate: '2026-07-01' },
      ],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-001', name: '新規顧客向け提案資料のレビュー' },
        { taskManagementNo: 'TK-2026-002', name: 'ログイン画面の表示崩れ調査' },
        { taskManagementNo: 'TK-2026-009', name: 'API 認証フロー統合テスト' },
      ],
      resourceFolders: [
        {
          id: 'fld-demo-001',
          name: '設計・参考リンク',
          entries: [
            { id: 'ent-demo-1', kind: 'url', title: 'UI キット（Figma）', href: 'https://www.figma.com' },
            { id: 'ent-demo-2', kind: 'file', title: '画面遷移図_ドラフト.pdf', href: '' },
          ],
        },
      ],
      lastUpdatedAt: '2026-05-08',
      lastUpdatedBy: '鈴木一郎',
      updateHistory: [
        {
          at: '2026-05-08',
          by: '鈴木一郎',
          changes: [{ kind: 'field', fieldLabel: '進捗率', newValue: '42%' }],
        },
        {
          at: '2026-05-05',
          by: '高橋健',
          changes: [{ kind: 'milestone_date', milestoneTitle: 'β版公開', newDate: '2026-07-01' }],
        },
        { at: '2026-04-28', by: '鈴木一郎', summary: '要件定義レビューを完了' },
        { at: '2026-04-10', by: '鈴木一郎', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-002',
      name: '営業支援ダッシュボード',
      description: '営業日報とパイプラインを可視化するダッシュボードの構築。',
      departments: ['営業第一部', '営業第二部', '総務'],
      endDate: '2026-07-20',
      priority: '中',
      registeredAt: '2026-02-10',
      workStartDate: '2026-03-01',
      completedAt: '',
      status: '着手中',
      participants: [
        { department: '営業第一部', name: '山田太郎', role: 'PM' },
        { department: '営業第二部', name: '佐藤花子', role: 'メンバー' },
        { department: '総務', name: '伊藤誠', role: 'メンバー' },
      ],
      members: ['山田太郎', '佐藤花子', '伊藤誠'],
      progressPercent: 65,
      approver: '鈴木一郎',
      milestones: [{ title: 'MVP リリース', targetDate: '2026-07-01' }],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-003', name: 'オフィス備品の発注' },
        { taskManagementNo: 'TK-2026-010', name: 'ダッシュボード KPI 定義' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-10',
      lastUpdatedBy: '山田太郎',
      updateHistory: [
        {
          at: '2026-05-10',
          by: '山田太郎',
          changes: [{ kind: 'field', fieldLabel: '進捗率', newValue: '65%' }],
        },
        {
          at: '2026-05-03',
          by: '佐藤花子',
          changes: [{ kind: 'field', fieldLabel: '担当部署', newValue: '営業第一部、営業第二部' }],
        },
        { at: '2026-04-12', by: '山田太郎', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2025-088',
      name: '社内文書テンプレート整備',
      description: '契約書・稟議などのテンプレート統一と保管ルールの策定。',
      departments: ['営業第二部'],
      endDate: '2026-06-30',
      priority: '低',
      registeredAt: '2025-11-01',
      workStartDate: '2025-12-01',
      completedAt: '2026-06-30',
      status: '完了',
      participants: [{ department: '営業第二部', name: '佐藤花子', role: '責任者' }],
      members: ['佐藤花子'],
      progressPercent: 100,
      approver: '山田太郎',
      milestones: [{ title: '本番運用開始', targetDate: '2026-06-30' }],
      relatedIssues: [{ taskManagementNo: 'TK-2026-011', name: 'テンプレ改訂履歴の整理' }],
      resourceFolders: [],
      lastUpdatedAt: '2026-06-30',
      lastUpdatedBy: '佐藤花子',
      updateHistory: [
        {
          at: '2026-06-30',
          by: '佐藤花子',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '完了' }],
        },
        {
          at: '2026-06-01',
          by: '佐藤花子',
          changes: [{ kind: 'field', fieldLabel: '完了日', newValue: '2026-06-30' }],
        },
        { at: '2025-12-05', by: '佐藤花子', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-010',
      name: 'インフラ監視強化',
      description: 'アラート閾値の見直しとオンブコール運用の整備。',
      departments: ['開発部'],
      endDate: '2026-07-08',
      priority: '急',
      registeredAt: '2026-04-01',
      workStartDate: '',
      completedAt: '',
      status: '保留',
      participants: [{ department: '開発部', name: '鈴木一郎', role: '責任者' }],
      members: ['鈴木一郎'],
      progressPercent: 18,
      approver: '佐藤花子',
      milestones: [],
      relatedIssues: [{ taskManagementNo: 'TK-2026-012', name: 'アラート閾値ドラフト見直し' }],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-01',
      lastUpdatedBy: '鈴木一郎',
      updateHistory: [
        {
          at: '2026-05-01',
          by: '鈴木一郎',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '保留' }],
        },
        {
          at: '2026-04-18',
          by: '鈴木一郎',
          changes: [{ kind: 'field', fieldLabel: 'プロジェクト内容', newValue: 'アラート閾値のドラフトを共有' }],
        },
        { at: '2026-04-05', by: '鈴木一郎', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-015',
      name: '新規顧客オンボーディング',
      description: '新規契約後の導入フローとキックオフ資料の標準化。',
      departments: ['営業第一部', '開発部'],
      endDate: '2026-07-05',
      priority: '高',
      registeredAt: '2026-04-15',
      workStartDate: '2026-05-01',
      completedAt: '',
      status: '確認待ち',
      participants: [
        { department: '営業第一部', name: '山田太郎', role: '責任者' },
        { department: '開発部', name: '鈴木一郎', role: 'PM' },
        { department: '開発部', name: '高橋健', role: 'メンバー' },
      ],
      members: ['山田太郎', '鈴木一郎', '高橋健'],
      progressPercent: 30,
      approver: '佐藤花子',
      milestones: [
        { title: 'キックオフ', targetDate: '2026-06-05' },
        { title: '初回レビュー', targetDate: '2026-06-25' },
      ],
      relatedIssues: [{ taskManagementNo: 'TK-2026-013', name: 'オンボーディングチェックリスト作成' }],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-11',
      lastUpdatedBy: '佐藤花子',
      updateHistory: [
        {
          at: '2026-05-11',
          by: '佐藤花子',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '確認待ち' }],
        },
        {
          at: '2026-05-09',
          by: '山田太郎',
          changes: [{ kind: 'field', fieldLabel: 'プロジェクト内容', newValue: 'キックオフ資料を更新' }],
        },
        {
          at: '2026-05-02',
          by: '鈴木一郎',
          changes: [{ kind: 'field', fieldLabel: '参加メンバー', newValue: '開発部メンバーを追加' }],
        },
        { at: '2026-04-20', by: '山田太郎', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-016',
      name: '社内 FAQ ポータル',
      description: '問い合わせの重複削減のため、部門別 FAQ と検索を一元化する。',
      departments: ['営業第一部', '営業第二部', '人事部'],
      endDate: '2026-07-25',
      priority: '中',
      registeredAt: '2026-05-01',
      workStartDate: '',
      completedAt: '',
      status: '未着手',
      participants: [
        { department: '営業第一部', name: '山田太郎', role: 'PM' },
        { department: '営業第二部', name: '佐藤花子', role: 'メンバー' },
        { department: '人事部', name: '加藤優子', role: 'メンバー' },
      ],
      members: ['山田太郎', '佐藤花子', '加藤優子'],
      progressPercent: 0,
      approver: '',
      milestones: [{ title: '要件ヒアリング', targetDate: '2026-06-15' }],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-004', name: 'KPI 定義ワークショップ準備' },
        { taskManagementNo: 'TK-2026-014', name: 'FAQ カテゴリ設計' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-01',
      lastUpdatedBy: '佐藤花子',
      updateHistory: [{ at: '2026-05-01', by: '佐藤花子', summary: 'プロジェクトを新規登録' }],
    },
    {
      managementNumber: 'PRJ-2026-017',
      name: 'モバイル印刷連携',
      description: 'スマートフォンからの安全な印刷キュー投入と部門別クォータ管理。',
      departments: ['開発部', 'マーケティング部'],
      endDate: '2026-07-18',
      priority: '高',
      registeredAt: '2026-04-22',
      workStartDate: '2026-05-05',
      completedAt: '',
      status: '着手中',
      participants: [
        { department: '開発部', name: '高橋健', role: '責任者' },
        { department: '開発部', name: '鈴木一郎', role: 'メンバー' },
        { department: 'マーケティング部', name: '石川奈々', role: 'メンバー' },
      ],
      members: ['高橋健', '鈴木一郎', '石川奈々'],
      progressPercent: 35,
      approver: '佐藤花子',
      milestones: [
        { title: 'PoC 完了', targetDate: '2026-06-20' },
        { title: '本番リリース', targetDate: '2026-07-15' },
      ],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-005', name: 'iOS での印刷プレビュー検証' },
        { taskManagementNo: 'TK-2026-015', name: '利用ガイド文面作成' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-12',
      lastUpdatedBy: '高橋健',
      updateHistory: [
        { at: '2026-05-12', by: '高橋健', summary: 'PoC 環境の疎通を確認' },
        { at: '2026-04-22', by: '高橋健', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-018',
      name: 'アクセス権レビュー（年度版）',
      description: '全システムのアカウント棚卸しと承認フローの見直し。',
      departments: ['開発部', '経理部'],
      endDate: '2026-07-12',
      priority: '急',
      registeredAt: '2026-04-08',
      workStartDate: '2026-04-15',
      completedAt: '',
      status: '確認待ち',
      participants: [
        { department: '開発部', name: '鈴木一郎', role: '責任者' },
        { department: '経理部', name: '井上剛', role: 'メンバー' },
      ],
      members: ['鈴木一郎', '井上剛'],
      progressPercent: 88,
      approver: '山田太郎',
      milestones: [{ title: 'レビュー完了', targetDate: '2026-07-10' }],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-006', name: '権限マトリクスドラフト作成' },
        { taskManagementNo: 'TK-2026-016', name: '棚卸結果サマリ作成' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-09',
      lastUpdatedBy: '鈴木一郎',
      updateHistory: [
        {
          at: '2026-05-09',
          by: '鈴木一郎',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '確認待ち' }],
        },
        { at: '2026-04-08', by: '鈴木一郎', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-019',
      name: 'VPN クライアント更新',
      description: '全社端末の VPN クライアントをベンダー推奨版へ一斉更新する。',
      departments: ['開発部', 'カスタマーサクセス'],
      endDate: '2026-07-10',
      priority: '高',
      registeredAt: '2026-03-10',
      workStartDate: '2026-03-15',
      completedAt: '2026-07-10',
      status: '完了',
      participants: [
        { department: '開発部', name: '高橋健', role: '責任者' },
        { department: 'カスタマーサクセス', name: '近藤真央', role: 'メンバー' },
      ],
      members: ['高橋健', '近藤真央'],
      progressPercent: 100,
      approver: '鈴木一郎',
      milestones: [{ title: '全端末展開完了', targetDate: '2026-07-10' }],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-007', name: '旧クライアントの切断エラー調査' },
        { taskManagementNo: 'TK-2026-017', name: '展開レポート最終確認' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-07-10',
      lastUpdatedBy: '高橋健',
      updateHistory: [
        {
          at: '2026-07-10',
          by: '高橋健',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '完了' }],
        },
        { at: '2026-03-10', by: '高橋健', summary: 'プロジェクトを新規登録' },
      ],
    },
    {
      managementNumber: 'PRJ-2026-020',
      name: 'メール署名統一ツール',
      description: '部署別テンプレートの配布と改定履歴の管理を行う社内ツール。',
      departments: ['営業第一部', '営業第二部', 'カスタマーサクセス'],
      endDate: '2026-07-28',
      priority: '低',
      registeredAt: '2026-04-28',
      workStartDate: '',
      completedAt: '',
      status: '保留',
      participants: [
        { department: '営業第一部', name: '山田太郎', role: '責任者' },
        { department: '営業第二部', name: '佐藤花子', role: 'メンバー' },
        { department: 'カスタマーサクセス', name: '坂本悠真', role: 'メンバー' },
      ],
      members: ['山田太郎', '佐藤花子', '坂本悠真'],
      progressPercent: 12,
      approver: '佐藤花子',
      milestones: [],
      relatedIssues: [
        { taskManagementNo: 'TK-2026-008', name: 'メールテンプレ差分一覧' },
        { taskManagementNo: 'TK-2026-018', name: 'テンプレ配布手順書作成' },
      ],
      resourceFolders: [],
      lastUpdatedAt: '2026-05-06',
      lastUpdatedBy: '山田太郎',
      updateHistory: [
        {
          at: '2026-05-06',
          by: '山田太郎',
          changes: [{ kind: 'field', fieldLabel: 'ステータス', newValue: '保留' }],
        },
        { at: '2026-04-28', by: '山田太郎', summary: 'プロジェクトを新規登録' },
      ],
    },
  ];
